### ISSUE TITLE
Missing screenshot files?

### ISSUE THREAD

**Issue by PySimpleGUI** [CTCycle/DataExplorer#1]
I would love to see the images you've added to your readme but the links don't point to image files

Here's one of the links in the readme:

https://github.com/CTCycle/Dataset-Explorer/assets/101833494/e619b8aa-a448-4558-9d00-385d58bbfe2e

**Comment by CTCycle** [comment]
I've replaced the old missing links with a new screenshot (where all the windows are shown in one shot). Thanks for letting me know that the links were not functional! On a related note, I'm planning to change the GUI by using gradio instead of PySimpleGUI, I'll update the screenshots once the transition is complete.
